# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5f4266eed0093b759b2bb014c42914b"
name = "HTML5 Audio Player"
handle = "html5-audio-player"
application_url = "https://sunset-fire-helen-hotel.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bp-first.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_script_tags,write_files,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://sunset-fire-helen-hotel.trycloudflare.com/auth/callback",
  "https://sunset-fire-helen-hotel.trycloudflare.com/auth/shopify/callback",
  "https://sunset-fire-helen-hotel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://appp-billowing-wave-6351.fly.dev/webhooks"
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]

[pos]
embedded = false
