# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5f4266eed0093b759b2bb014c42914b"
name = "Audio Player by bPlugins"
handle = "audio-player-by-bplugins"
application_url = "https://appp-solitary-morning-3913.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bp-first.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_script_tags,write_files,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://appp-solitary-morning-3913.fly.dev/auth/callback",
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://appp-solitary-morning-3913.fly.dev/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]


[pos]
embedded = false
